rpjproost/Context-project-Health-informatics-2

- src/main/java/context/healthinformatics/Parser/TXTParser.java
- src/test/data/txtparsertestfiles/correcttest.txt
- src/test/java/context/healthinformatics/Parser/TXTParserTest.java
Adjust input file for txt parser test.
Added test to TXTParserTest.
Added a method to txtparser to check if lines can be checked.
> TXTParser got 100% test coverage!

- src/main/java/context/healthinformatics/GUI/InputPage.java
> added features to InputPage

- .travis.yml
- pom.xml
- src/main/java/context/healthinformatics/GUI/CodePage.java
- src/main/java/context/healthinformatics/GUI/InputPage.java
- src/main/java/context/healthinformatics/GUI/MainFrame.java
> Analyze tab

- .travis.yml
> Travis edit

- src/main/java/context/healthinformatics/GUI/OutputPage.java
Button creation for outputting the analyzed data
> Output page

- src/main/java/context/healthinformatics/Database/SingletonDb.java
- src/main/java/context/healthinformatics/Parser/Column.java
- src/test/java/context/healthinformatics/Database/DbTest.java
- src/test/java/context/healthinformatics/Parser/ColumnTest.java
-Will be adding issue for static path and name singletonDB
-Added tests for singletonDB
-Added tests for Column (100% test coverage now)
-Added getters and setters for SingletonDB
-Added javadoc for Column.
> Tests for singletonDB and column

- src/main/java/context/healthinformatics/GUI/InputPage.java
- src/test/java/context/healthinformatics/GUI/InputPageTest.java
- src/test/java/context/healthinformatics/GUI/MainFrameTest.java
InputPage has been mannualy tested.
> Input page

- src/main/java/context/healthinformatics/Analyse/Interpreter.java
- src/main/java/context/healthinformatics/Analyse/SingletonInterpreter.java
> Interpreter

- src/main/java/context/healthinformatics/Database/Db.java
- src/main/java/context/healthinformatics/Database/MergeTable.java
- src/main/java/context/healthinformatics/Database/SqlBuilder.java
- src/main/java/context/healthinformatics/GUI/OutputPage.java
- src/main/java/context/healthinformatics/SequentialDataAnalysis/Constraints.java
- src/test/java/context/healthinformatics/Database/DbTest.java
- src/test/java/context/healthinformatics/Database/MergeTableTest.java
- src/test/java/context/healthinformatics/ParserToDB/ParserToDBTest.java
- src/test/java/context/healthinformatics/Writer/WriterTest.java
Edited a lot of files in the process of cleaning up database, because of
deletion of unused method, or extending them with more variables.
-Created new class SQLBuilder
This creates every query we use, database has no more string
concatenation.
Every method is as small as possible, and long method names.
-DB class
Removed a lot of methods, switched them over to SQLBuilder and adjusted
them accordingly.
Also renamed an method and added more variables to a method.
We had 3 different select methods?....
Removed one entirely, adjusted the other two to be different kind of
selects.
-Tests
Mostly changed tests that were running that one select I entirely
removed. Also adjusted some lines so they would work with the two
different select methods.
-All
- no checkstyle warnings
- no PMD/CPD
- …
> Database clean up

- src/main/java/context/healthinformatics/Parser/ExcelParser.java
- src/main/java/context/healthinformatics/Parser/TXTParser.java
Made methods which should be private, private and split some long methods into smaller ones.
> CleanedUp the ExcelParser and TXTParser Class.

- src/main/java/context/healthinformatics/SequentialDataAnalysis/Constraints.java
> Fixed JavaDoc int he Constraints Class. Discovered a few spell check

- src/main/java/context/healthinformatics/GUI/FileTree.java
- src/main/java/context/healthinformatics/GUI/InputPage.java
- src/main/java/context/healthinformatics/GUI/InputPageComponents.java
- src/main/java/context/healthinformatics/GUI/InterfaceHelper.java
- src/test/java/context/healthinformatics/GUI/InputPageTest.java
Cleaned up InputPage class.
Divided in FileTree and InputPAgeComponents.
Tests altered accordingly.
> Gui clean up

- src/main/java/context/healthinformatics/Database/MergeTable.java
- src/main/java/context/healthinformatics/Parser/ExcelParser.java
- src/main/java/context/healthinformatics/Parser/TXTParser.java
- src/main/java/context/healthinformatics/Parser/XMLParser.java
- src/main/java/context/healthinformatics/SequentialDataAnalysis/Comments.java
- src/test/java/context/healthinformatics/ParserToDB/ParserToDBTest.java
- src/test/java/context/healthinformatics/SequentialDataAnalysis/CommentsTest.java
Made a few changes to errorhandling. Instead of printing stacktrace now logs to console.
> Error handeling improved

- src/main/java/context/healthinformatics/SequentialDataAnalysis/Connections.java
- src/test/java/context/healthinformatics/SequentialDataAnalysis/ConnectionsTest.java
Connection class implemented, and test class made.
> Connections

- src/main/java/context/healthinformatics/gui/FileTree.java
- src/main/java/context/healthinformatics/gui/InputPage.java
- src/main/java/context/healthinformatics/gui/InputPageComponents.java
- src/test/java/context/healthinformatics/gui/InputPageTest.java
Removed the TextField and changed the buttons.
> Input page adjustment

- pom.xml
- src/main/java/context/healthinformatics/gui/CodePage.java
- src/main/java/context/healthinformatics/gui/InterResultController.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Chunking.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Tasks.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/ChunkingOnDataTest.java
- Adjusted pom.xml for quicker result maven site
- adjusted codepage for showing intermediate result(not finished)
- added interResultController (not finished)
- added tasks (all c's will extend this class)
- adjusted Chunking (works with chunking on sql queries now)
- added test for chunking on data
> Chunking on sql queries is working now.

- src/main/java/context/healthinformatics/sequentialdataanalysis/Codes.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/CodeOnDataTest.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/CodesTest.java
Updated Codes with new functionality.
Updated tests accordingly.
> Codes update

- src/main/java/context/healthinformatics/sequentialdataanalysis/Comments.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/CommentOnDataTest.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/CommentsTest.java
added functionality to Comment, for the interpreter to use. Changed Tests accordingly.
> Comment update

- .gitignore
- src/main/java/context/healthinformatics/gui/InputPage.java
- src/main/java/context/healthinformatics/interfacecomponents/InputPageComponents.java
- src/main/java/context/healthinformatics/interfacecomponents/XMLEditor.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/ChunkingOnDataTest.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/CodeOnDataTest.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/CommentOnDataTest.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/ConnectionOnDataTest.java
Fixed some problems with input page
> Fix master problems

- src/main/data/guihelpdata/codepagehelp.txt
added help text for the CodePage
> Analysis tab help text

- src/main/java/context/healthinformatics/gui/MainFrame.java
Fixed action listener of tabs.
> Fixed actionlistener of switching between tabs.

- src/test/java/context/healthinformatics/gui/MainFrameTest.java
> Fixed two failures because we changed the change tabs event to

- src/main/java/context/healthinformatics/sequentialdataanalysis/Task.java
These methods were not working. Now they are
> fixed contains/equals on comment

- src/main/java/context/healthinformatics/sequentialdataanalysis/Connections.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/ChunkingOnDataTest.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/ConnectionsTest.java
> Connection tests

- src/main/java/context/healthinformatics/interfacecomponents/InputPageComponents.java
Set a loadingscreen variabel to final because I had an error.
> Fixed an error that only I had. Set an variabel to final.

- pom.xml
- src/main/java/context/healthinformatics/interfacecomponents/DocumentFieldsContainer.java
- src/test/java/context/healthinformatics/gui/MainFrameTest.java
- src/test/java/context/healthinformatics/interfacecomponents/ColumnFieldContainerTest.java
- src/test/java/context/healthinformatics/interfacecomponents/DocumentFieldsContainerTest.java
- src/test/java/context/healthinformatics/interfacecomponents/XMLEditorControllerTest.java
Added mockito to the pom
created some tests classes for the components
changed some test in the mainframe
> Components tests

- src/main/java/context/healthinformatics/gui/CodePage.java
- src/main/java/context/healthinformatics/gui/InterfaceHelper.java
- src/main/java/context/healthinformatics/gui/OutputPage.java
- src/main/java/context/healthinformatics/interfacecomponents/IntermediateResults.java
- src/test/java/context/healthinformatics/gui/OutputPageTest.java
Created skeleton for the output page
> Output page interface

- src/main/java/context/healthinformatics/sequentialdataanalysis/Connections.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/ConnectionsTest.java
Now only connects to first occurance in the destination List.
ALso added Tests.
> Connection update

- src/main/java/context/healthinformatics/sequentialdataanalysis/Chunking.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Codes.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Comments.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Computations.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Connections.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Constraints.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Task.java
added selection by line as a option.
> Selection by line

- src/main/java/context/healthinformatics/analyse/Interpreter.java
> undoAll functionallity added.

- src/main/java/context/healthinformatics/interfacecomponents/InputPageComponents.java
Made some methods private that are used locally.
Deleted some getters that weren't been used.
No PMD, CPD, FindBugs or CheckStyle introduced
> Fix the input page components class, not schizoprenic anymore

- src/test/java/context/healthinformatics/interfacecomponents/DocumentFieldsContainerTest.java
Please merge asap. Master test fix.
> Fixed failure + checkstyle.

- src/main/java/context/healthinformatics/interfacecomponents/XMLDocumentFormController.java
- src/main/java/context/healthinformatics/interfacecomponents/XMLEditor.java
Fixed little bug where numbers were not check correctly.
> Fixed bug where numbers were not checked.

- src/main/java/context/healthinformatics/gui/CodePage.java
- src/main/java/context/healthinformatics/gui/InterfaceHelper.java
- src/main/java/context/healthinformatics/gui/OutputPage.java
- src/main/java/context/healthinformatics/parser/ReadHelpInfoFromTXTFile.java
- src/main/java/context/healthinformatics/writer/WriteToTXT.java
We now can import and save script files in the analyze page.
> Implemented a reader and writer to import and save scripts

- src/main/java/context/healthinformatics/interfacecomponents/XMLDocumentFormController.java
- src/test/java/context/healthinformatics/interfacecomponents/XMLDocumentFormControllerTest.java
> Implemented the test for XMLDocumentFormController.

- src/main/java/context/healthinformatics/gui/InputPage.java
- src/test/java/context/healthinformatics/writer/WriterTest.java
Implemented WriterTest. 97,4% test coverage.
> Fixed possible null pointer findbug in InputPage.

- src/main/java/context/healthinformatics/sequentialdataanalysis/Codes.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Comments.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/CodesTest.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/CommentsTest.java
> fixed codes and comments on contains comment.

- src/main/java/context/healthinformatics/analyse/Interpreter.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Chunk.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Chunking.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/ComputationData.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/ComputationDataTest.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/ComputationsTest.java
Fixed chunking on data
added undo feature for computation
added tests for computationData
> Computation undo and test

- src/main/java/context/healthinformatics/gui/InputPage.java
- src/main/java/context/healthinformatics/interfacecomponents/FileTree.java
- src/main/java/context/healthinformatics/parser/XMLParser.java
- src/test/java/context/healthinformatics/gui/InputPageTest.java
No PMD, CPD, Checkstyle or FindBugs :+1:
> Fix data class

- src/main/java/context/healthinformatics/gui/MainFrame.java
- src/main/java/context/healthinformatics/help/HelpFrame.java
- src/main/java/context/healthinformatics/interfacecomponents/AnalysePopupRowContainer.java
- src/main/java/context/healthinformatics/interfacecomponents/GoToAnalysePopup.java
- src/main/java/context/healthinformatics/interfacecomponents/GoToAnalysePopupController.java
- src/main/java/context/healthinformatics/interfacecomponents/XMLEditorController.java
Removed system.out from HelpFrame.
Reworked the Analyse popuprow container to be able to add infinite
number of filters.
Also able to save zero filters.
And filters are now deleted when a project is removed.
> Fixed Pre Filters.

- src/main/data/savedFilters/(default).txt
- src/main/java/context/healthinformatics/sequentialdataanalysis/Chunk.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Chunking.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Codes.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Comments.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Comparison.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/ComputationData.java
- src/main/java/context/healthinformatics/sequentialdataanalysis/Computations.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/CodesTest.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/ComparisonTest.java
cleaning of seq data analysis package
> Seq data analysis clean up

- src/main/java/context/healthinformatics/help/HelpFrame.java
> Adjusted some javadoc.

- src/main/java/context/healthinformatics/interfacecomponents/XMLEditorController.java
- src/main/java/context/healthinformatics/writer/ReadWriteAnalyseFilter.java
- src/main/java/context/healthinformatics/writer/ScreenImage.java
- src/main/java/context/healthinformatics/writer/WriteToTXT.java
- src/main/java/context/healthinformatics/writer/XMLWriter.java
- src/test/java/context/healthinformatics/writer/XMLWriterTest.java
CleanedUp ReadWriterAnalyseFilter.
CleanedUp ScreenIMG.
CleandUp WriteToTXT.
CleanedUp XMLWriter.
Adjusted XMLWriterTest.
> Handled error from XMLWriter in XMLEditroController.

- src/main/java/context/healthinformatics/sequentialdataanalysis/Chunk.java
> removed amount of childs

- src/main/java/context/healthinformatics/sequentialdataanalysis/Chunking.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/ComputationDataTest.java
- src/test/java/context/healthinformatics/sequentialdataanalysis/ComputationsTest.java
fixes for tests because of changes in toArray
> fixes for chunking PMD
